name: Run JMeter Basic Stress Test

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    services:
      influxdb:
        image: influxdb:1.8
        ports:
          - 8086:8086
        env:
          INFLUXDB_DB: jmeter
          INFLUXDB_ADMIN_USER: admin
          INFLUXDB_ADMIN_PASSWORD: admin123
          INFLUXDB_HTTP_AUTH_ENABLED: "true"
        options: >-
          --health-cmd "curl -f http://localhost:8086/ping || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      grafana:
        image: grafana/grafana
        ports:
          - 3000:3000
        env:
          GF_SECURITY_ADMIN_USER: admin
          GF_SECURITY_ADMIN_PASSWORD: admin
        volumes:
          - ./provisioning:/etc/grafana/provisioning
          - ./grafana/dashboards:/var/lib/grafana/dashboards

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download and Extract JMeter
        run: |
          wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz

      - name: Run JMeter Test
        run: |
          python run_test.py --test-type stress --env config/env_config.yml --skip-monitoring
